HotelHero.WebMVC/Controllers/AdminPanelController.cs
using HotelHero.ReservationsDatabase;
using HotelHero.WebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using HotelHero.WebMVC.Interface;
using HotelHero.HotelsDatabase;
using Newtonsoft.Json;

namespace HotelHero.WebMVC.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly IFileOperationService _fileOperationService;
        private readonly IAdminService _adminService;
        public AdminPanelController(IFileOperationService fileOperationService, IAdminService adminService)
        {
            _fileOperationService = fileOperationService;
            _adminService = adminService;
        }
        // GET: AdminPanelController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminPanelController/Users
        public ActionResult Users()
        {
            var model = _fileOperationService.GetUsers();
            return View(model);
        }
        public ActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(User user)
        {
            _fileOperationService.CreateUser(user.Email, user.Password);
            return RedirectToAction("Users");
        }

        // GET: AdminPanelController/Edit
        public ActionResult EditUser(int id)
        {
            var model = _fileOperationService.GetUser(id);
            return View(model);
        }

        // POST: AdminPanelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(int id, User user)
        {
            _fileOperationService.EditUser(id, user);
            return RedirectToAction("Users");
        }

        // GET: AdminPanelController/Delete
        public ActionResult DeleteUser(int id)
        {
            var model = _fileOperationService.GetUser(id);
            return View(model);
        }

        // POST: AdminPanelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUser(int id, IFormCollection collection)
        {
            _fileOperationService.DeleteUser(id);
            return RedirectToAction("Users");
        }

        public ActionResult AdditionalServicesList()
        {
            var model = _adminService.GetAdditionalServicesList();
            return View(model);
        }

        public ActionResult CreateAdditionalService()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdditionalService(AdditionalService additionalService)
        {
            _adminService.SaveAdditionalServiceToList(additionalService);
            return RedirectToAction("AdditionalServicesList");
        }
        public ActionResult EditAdditionalService(int id)
        {
            var model = _adminService.GetAdditionalService(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAdditionalService(AdditionalService additionalService)
        {
            _adminService.EditAdditionalService(additionalService);
            return RedirectToAction("AdditionalServicesList");
        }
        public ActionResult DeleteAdditionalService(int id)
        {
            _adminService.DeleteAdditionalService(id);
            return RedirectToAction("AdditionalServicesList");
        }
    }
}

HotelHero.WebMVC/Controllers/CustomerPanelController.cs
using Microsoft.AspNetCore.Mvc;
using HotelHero.WebMVC.Interface;
using HotelHero.HotelsDatabase;
using HotelHero.WebMVC.Models;
using Hotel = HotelHero.WebMVC.Models.Hotel;

namespace HotelHero.WebMVC.Controllers
{
    public class CustomerPanelController : Controller
    {
        private readonly IHotelService _hotelsRepository;
        private readonly ICustomerDataService _customerDataService;
        private readonly IReservationService _reservationService;
        private readonly IPaymentService _paymentService;

        public CustomerPanelController(IHotelService hotelsRepository, ICustomerDataService customerData, IReservationService reservationService, IPaymentService paymentService)
        {
            _hotelsRepository = hotelsRepository;
            _customerDataService = customerData;
            _reservationService = reservationService;
            _paymentService = paymentService;
        }

        // GET: CustomerPanelController
        public ActionResult CustomerPanel()
        {
            return View();
        }
        public ActionResult CustomerData()
        {
            var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            return View(customerData);
        }

        // GET: CustomerPanelController/Edit/5
        public ActionResult CustomerDataEdit(int customerUserId)
        {
            var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            return View(customerData);
        }

        // POST: CustomerPanelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerDataEdit(int customerID, CustomerData data)
        {
            _customerDataService.EditCustomerData(data);
            return RedirectToAction("CustomerData");
        }
        public ActionResult Reservations()
        {
            var model = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId).Reservations;
            if(model == null)
            {
                model = new();
            }
            return View(model);
        }
        public ActionResult CancelReservation(int id)
        {
            _customerDataService.CancelReservation(id);
            _reservationService.CancelReservation(id);
            return RedirectToAction("Reservations");
        }
        public ActionResult PaymentsHistory()
        {
            var paymentsHistory = _paymentService.GetPaymentHistory();
            var model = paymentsHistory.Where(x => x.UserId == UserContext.loggedUser.UserId).ToList();
            return View(model);
        }
        public ActionResult Favourites()
        {
            List<Hotel> model = new();
            var customerFavourites = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId).Favourites;
            if (customerFavourites != null)
            {
                foreach (var item in customerFavourites)
                {
                    var hotel = _hotelsRepository.GetHotel(item);
                    model.Add(hotel);
                }
            }
            return View(model);
        }
        public ActionResult Unfavourite(int id)
        {
            var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            customerData.Favourites.Remove(id);
            _customerDataService.EditCustomerData(customerData);
            return RedirectToAction(nameof(Favourites));
        }
        public ActionResult FavouriteDetails(int id)
        {
            var model = _hotelsRepository.GetHotel(id);
            return View(model);
        }
        public ActionResult Wallet()
        {
            var model = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            return View(model);
        }
        public ActionResult AddBalance()
        {
            var data = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBalance(string amount)
        {
            var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
            var parsed = decimal.TryParse(amount, out var balance);
            if (parsed)
            {
                customerData.Balance += balance;
                _customerDataService.EditCustomerData(customerData);
                return RedirectToAction(nameof(Wallet));
            }
            else
            {
                return RedirectToAction(nameof(AddBalance));
            }
        }
    }
}

HotelHero.WebMVC/Controllers/HotelsController.cs
using Microsoft.AspNetCore.Mvc;
using HotelHero.WebMVC.Interface;
using HotelHero.WebMVC.Models;
using HotelHero.WebMVC.ViewModels;

namespace HotelHero.WebMVC.Controllers
{
    public class HotelsController : Controller
    {
        private readonly IHotelService _hotelsRepository;
        private readonly IReservationService _reservationService;
        private readonly ICustomerDataService _customerDataService;

        public HotelsController(IHotelService hotelsRepository, ICustomerDataService customerData, IReservationService reservationService)
        {
            _hotelsRepository = hotelsRepository;
            _customerDataService = customerData;
            _reservationService = reservationService;
        }


        public ActionResult Index()
        {
            var model = _hotelsRepository.GetHotels();
            return View(model);
        }

        // GET: HotelsController/Details/5
        public ActionResult Details(int id)
        {
            var model = new HotelDetailViewModel();
            model.Hotel = _hotelsRepository.GetHotel(id);
            model.ReservationDatas = _reservationService.GetReservationForHotel(id);
            return View(model);
        }

        public ActionResult Favourite(int id)
        {
            try
            {
                var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
                if (customerData.Favourites == null)
                {
                    customerData.Favourites = new List<int> { };
                }
                customerData.Favourites.Add(id);
                _customerDataService.EditCustomerData(customerData);
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Unfavourite(int id)
        {
            try
            {
                var customerData = _customerDataService.GetCustomerData(UserContext.loggedUser.UserId);
                if (customerData.Favourites == null)
                {
                    customerData.Favourites = new List<int> { };
                }
                customerData.Favourites.Remove(id);
                _customerDataService.EditCustomerData(customerData);
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: HotelsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HotelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hotel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                _hotelsRepository.Create(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotelsController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _hotelsRepository.GetHotel(id);
            return View(model);
        }

        // POST: HotelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Hotel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                _hotelsRepository.Update(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotelsController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _hotelsRepository.GetHotel(id);
            return View(model);
        }

        // POST: HotelsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _hotelsRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult MakeReservation(int id)
        {
            return RedirectToAction("MakeReservation", "Search", new { id = id});
        }
    }
}

HotelHero.WebMVC/Controllers/LogInController.cs
using HotelHero.WebMVC.Models;
using HotelHero.WebMVC.Interface;
using HotelHero.WebMVC.Models;
using HotelHero.WebMVC.Services;
using Microsoft.AspNetCore.Mvc;
using HotelHero.WebMVC.ViewModels;

namespace HotelHero.WebMVC.Controllers
{
    public class LogInController : Controller
    {
        private readonly ILogInService _logInService;
        private readonly ICustomerDataService _customerDataService;
        private readonly IFileOperationService _fileOperationService;

        public LogInController(ILogInService logService, ICustomerDataService customerDataService, IFileOperationService fileOperationService)
        {
            _logInService = logService;
            _customerDataService = customerDataService;
            _fileOperationService = fileOperationService;
        }
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(User user)
        {
            try
            {
                //if (!ModelState.IsValid)
                //{
                //    return View(user);
                //}
                _logInService.LogIn(user);
                return RedirectToAction(nameof(HomeController.Index), "Search");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult LogOut()
        {
            _logInService.LogOut();
			return RedirectToAction(nameof(HomeController.Index), "Search");
		}

        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterUserViewModel user)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(user);
                }
                var registeredUser = _fileOperationService.CreateUser(user.Email, user.Password);
                return RedirectToAction("RegisterCustomerData");
            }
            catch
            {
                return View();
            }
        }
        public IActionResult RegisterCustomerData()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterCustomerData(CustomerData customerData)
        {
            var data = new CustomerData(
                UserContext.loggedUser.UserId,
                UserContext.loggedUser.Email,
                customerData.LastName,
                customerData.FirstName,
                customerData.DateOfBirth,
                customerData.Address,
                customerData.Phone,
                new List<Reservation>(),
                new List<int>(),
                customerData.Rodo,
                customerData.Newsletter,
                0m
                );

            _customerDataService.CreateCustomerData(data);
            return RedirectToAction("Index", "Home");
        }
    }
}

HotelHero.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelHero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/customStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelHero.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary bg-opacity-60  border-bottom box-shadow mb-3" style="background: linear-gradient(to top right, #66ff99 0%, #0000ff 100%);">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Search" asp-action="Index">HOTEL HERO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Hotels" asp-action="Index">Hotels</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @if (UserContext.GetUser() != null)
                    {
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @UserContext.GetUser()?.Email
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-custom">
                                @if (UserContext.GetUser() != null && UserContext.GetUser()?.UserRole != HotelHero.UserPanel.Enums.UserRole.Admin)
                                {
                                    <li><a class="dropdown-item text-white" asp-area="" asp-controller="CustomerPanel" asp-action="CustomerPanel">Customer Panel</a></li>
                                }
                                @if (UserContext.GetUser()?.UserRole == HotelHero.UserPanel.Enums.UserRole.Admin)
                                {
                                    <li>
                                        <a class="dropdown-item text-white" asp-area="" asp-controller="AdminPanel" asp-action="Index">Administrator Panel</a>
                                    </li>
                                }
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item text-white" asp-area="" asp-controller="LogIn" asp-action="LogOut">Logout</a></li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="LogIn" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="LogIn" asp-action="LogIn">Login</a>
                                </li>
                            </ul>
                        </div>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="vertical-align:bottom">
        <div class="container">
            &copy; 2024 - HotelHero
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>